#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-or-later
# Set up clangd for an ESP-IDF project by writing .clangd in its root.
#
#   . "$IDF_PATH/export.sh"                        # puts Espressif's clangd on PATH
#   cd my-esp-project && /path/to/vim-c-env/scripts/esp-clangd-setup.sh
#
# Why: compile_commands.json from ESP-IDF carries GCC-only flags clangd rejects,
# and Espressif's clangd package ships without clang's builtin headers
# (stdbool.h, stddef.h, ...). The .clangd written here removes those flags and
# points clangd at the headers from the esp-clang toolchain.
set -euo pipefail

root="${1:-$PWD}"
if ! grep -qs 'tools/cmake/project.cmake' "$root/CMakeLists.txt"; then
  echo "not an ESP-IDF project root (no project.cmake include): $root" >&2
  exit 1
fi
if [ -z "${IDF_PATH:-}" ]; then
  echo "IDF_PATH is not set; run: . \"\$IDF_PATH/export.sh\" (or get_idf) first" >&2
  exit 1
fi

tools="${IDF_TOOLS_PATH:-$HOME/.espressif}/tools"
# Prints the newest esp-clang resource dir, or nothing (also when none is installed).
find_res() {
  { find "$tools/esp-clang" -path '*/esp-clang/lib/clang/*/include/stdbool.h' 2>/dev/null || true; } \
    | sort -V | tail -1 | sed 's|/include/stdbool.h$||'
}

res="$(find_res)"
if [ -z "$res" ]; then
  echo ">> installing esp-clang (provides clang's builtin headers)"
  python3 "$IDF_PATH/tools/idf_tools.py" install esp-clang
  res="$(find_res)"
fi
if [ ! -d "$tools/esp-clangd" ]; then
  echo ">> installing esp-clangd (Espressif's clangd, which knows Xtensa)"
  python3 "$IDF_PATH/tools/idf_tools.py" install esp-clangd || true
fi
[ -n "$res" ] || { echo "could not find esp-clang's builtin headers under $tools" >&2; exit 1; }

cat > "$root/.clangd" <<EOF
# Generated by vim-c-env scripts/esp-clangd-setup.sh for ESP-IDF.
CompileFlags:
  Remove:
    - -fno-malloc-dce
    - -fno-shrink-wrap
    - -fno-tree-switch-conversion
    - -fstrict-volatile-bitfields
    - -fzero-init-padding-bits=*
    - -mlongcalls
    - -mdisable-hardware-atomics
    - -mtune=*
    - -mcpu=esp*
  Add:
    - -resource-dir=$res
EOF
echo "wrote $root/.clangd (builtin headers: $res)"

clangd_now="$(command -v clangd || true)"
case "$clangd_now" in
  *esp-clangd*) echo "clangd on PATH is Espressif's: $clangd_now" ;;
  *) echo "note: clangd on PATH is not Espressif's (${clangd_now:-none})."
     echo "      Start vim from a shell where '. \$IDF_PATH/export.sh' ran;"
     echo "      ESP32, ESP32-S2 and ESP32-S3 (Xtensa) need Espressif's clangd." ;;
esac
